name: Docker Image CI

on:
  push:
    branches: ["develop"]

  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build ./API --file ./API/Dockerfile --tag acedema/api:latest && \
          docker tag acedema/api:latest ghcr.io/acedema/api:${{ github.sha } && \
          docker push ghcr.io/acedema/api:${{ github.sha }
